### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by indus** [monkberry/monkberry#15]
I haven´t seen any information about that.

**Comment by elfet** [comment]
Hi, i'll add it soon. Also I planing to run all my tests in browserstack.

**Comment by elfet** [comment]
Now Monkberry supports IE9+, Firefox 4+, Chrome 15+, Opera 12.1+ Safari 5+, Edge 13+, iOS 5+, Android 4+.

**Comment by indus** [comment]
Good to know. This may sound a bit stupid, but do you think there is a chance for a IE8 legacy version or is there ans hard show stopper. I've had a look to monkberry.js so far and it looks not to hard but it would also depend a lot on the compiled templates of course (e.g. eventListeners etc.)

**Comment by elfet** [comment]
Monkberry uses only createElement and setAttribute. So I think it's possible to run on IE8. But a lot of libraries will need a lot of polyfills.

**Comment by indus** [comment]
You mean other external libraries, right? 
Sure IE8 is more pain then ever (for a good reason)

Thanks for the fast answers and :+1: for your work.
