### ISSUE TITLE
Add DBMonster benchmark

### ISSUE THREAD

**Issue by 0x8890** [monkberry/monkberry#26]
It would be nice to see how monkberry performs compared to other libs:
http://mathieuancelin.github.io/js-repaint-perfs/

**Comment by elfet** [comment]
Hi,

You can add it there your self. We have our own benchmarks: http://monkberry.js.org/benchmark/

**Comment by PierBover** [comment]
It's already there and running great:
http://mathieuancelin.github.io/js-repaint-perfs/monkberry/index.html

**Comment by elfet** [comment]
Awesome!

**Comment by 0x8890** [comment]
Nice :)
