### ISSUE TITLE
No Access to Outer Scope, within if inside for loop?

### ISSUE THREAD

**Issue by Nexxtron** [monkberry/monkberry#32]
Hey,
at first, I want to say thank you, for this brilliant Library.

Now to the actual Problem. I am currently writing a complex UserInterface where I need multiple conditions and "for"-loops inside each other. But I can´t access the outer Scope variables inside a "if"-condition within a "for"-loop...

Documentation says:
"To access outer scope specify iterator name."
-> `{% for user of array %}
{{ user.name }}
{% endfor %}`

Here is the Fiddle to demonstrate where I can´t have access to the Outer Scope Property "outer":
https://jsfiddle.net/cjb207sr/4/

-> And when I update the View a second Time the Outer Scope works:
https://jsfiddle.net/cjb207sr/5/

Is this intended? Or a bug?

**Comment by elfet** [comment]
Hi, this looks like bug for me. 

I will take a look as soon as possible.

**Comment by elfet** [comment]
Fixed in [4.0.8](https://github.com/monkberry/monkberry/commit/6c232c61dac202a614e4952a677559a36f347820).

**Comment by Nexxtron** [comment]
Thank you, very much!
