### ISSUE TITLE
Image insertion

### ISSUE THREAD

**Issue by wadeV12** [monkberry/monkberry#41]
When i am trying to put image in template i always got error:

> Tag identifiers should be same (<img> != </div>) while parsing file.

So here is code: 
```html
<img src="{{ barcode_img_src }}" alt="">
```
And it's not working. But this code works:
```html
<img src="{{ barcode_img_src }}" alt=""></img>
```

**Comment by elfet** [comment]
Correct, all tags should be closed (except br, link and a few more). You can use this: 
`<img src="{{ barcode_img_src }}" alt=""/>`
