### ISSUE TITLE
Why endif, endfor etc. rather than end?

### ISSUE THREAD

**Issue by chocolateboy** [monkberry/monkberry#43]
Is there a reason why there are multiple end tags rather than simply using `end`? i.e. instead of:

```twig
<ol>
  {% for todos %}
    <li>
      {% if complete %}
        <del>{{ text }}</del>
      {% else %}
        <em>{{ text }}</em>
      {% endif %}
    </li>
  {% endfor %}
</ol>
```

\- why not:

```erb
<ol>
  {% for todos %}
    <li>
      {% if complete %}
        <del>{{ text }}</del>
      {% else %}
        <em>{{ text }}</em>
      {% end %}
    </li>
  {% end %}
</ol>
```
?

Are there any plans to migrate to a single end tag, or any interest in a pull request to do so?

**Comment by daliwali** [comment]
Seems to be inspired by PHP's `endif` :)

**Comment by DylanPiercey** [comment]
Imo makes reading easier.

**Comment by antonmedv** [comment]
> Imo makes reading easier.
Agree.

**Comment by antonmedv** [comment]
No plans for migrating to "end". Sorry.
