### ISSUE TITLE
Where to put directive with browserify setup? 

### ISSUE THREAD

**Issue by Abdillah** [monkberry/monkberry#44]
Hi @antonmedv ,
I love this library as it does what it should!

But, I have a question. 
I have a setup where `monkberry` used with browserify. It compiles all `monk` files and include it elsewhere. The think is, I have no way (in my knowledge) to specify directive to use.

Can I put what directives to use directly in my `*.monk` file? 
```
{% import directives from 'monkberry-directives' %}

<div :show="{{ variable }}">...</div>
```

Or in my class which extend the generated Template class?
```
import directives from 'monkberry-directives';

class View extends Template {
    constructor() {
         super();
         this.directives = directives;
    }
}
```
Which both happen to do nothing.. 

Am I make mistake?

**Comment by antonmedv** [comment]
```js
import Monkberry from 'monkberry';
import Template from 'template.monk';
import directives from 'monkberry-directives';

const view = Monkberry.render(Template, document.body, {directives});
```

More at https://monkberry.js.org/docs/directives

**Comment by Abdillah** [comment]
I'm sorry, yeah, that's the case!
Thank you..

Just curious, is there currently other way to include directives from `.monk` or class directly?

**Comment by antonmedv** [comment]
I think no.

**Comment by Abdillah** [comment]
Okay, thaks
